# === Informasi Dasar Situs ===
title: Amirullah310's Blog
description: Personal blog powered by Jekyll and GitHub Pages
url: 'https://amirullah310.github.io'  # URL utama situs
baseurl: ''  

# === Info Penulis ===
author:
  name: Amirullah
  email: amirullah.lsm99@gmail.com

# === SEO & Sosial (opsional) ===
social_links:
  github: https://github.com/amirullah310
  linkedin: https://www.linkedin.com/in/amirullah310/
  twitter: https://twitter.com/amirullah310

# === Plugin ===
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag